根据是否更新条件周期性的提交pr
openyurtio/yurt-edgex-manager pull request #85
Opened 2023-02-15 14:39 UTC by yangbobo6

#### What type of PR is this?
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
/kind feature
/sig iot

#### What this PR does / why we need it:
Set a timing trigger to enable the EdgeX Auto-Collector to periodically synchronize.

#### Which issue(s) this PR fixes:
Fixes #64 #65 

#### Special notes for your reviewer:

2023-02-17 04:15 UTC, LavenderQAQ commented
Issue #64  also need to modify the e2e test.This pr only addresses issue #65.

2023-02-17 04:45 UTC, LavenderQAQ requested changes

2023-02-17 04:45 UTC, LavenderQAQ commented on .github/workflows/auto-submit-pr.yaml
> +#   schedule:
We need to open the button of periodically launching.

2023-02-17 04:45 UTC, LavenderQAQ commented on EdgeXConfig/manifest.yaml
> +    - main
We currently only have five valid versions, and the extra versions do not need to appear in the manifest.
```yaml
versions:
   - levski
   - kamakura
   - jakarta
   - ireland
   - hanoi
```

2023-02-17 04:50 UTC, LavenderQAQ commented
I have a question, do we need a separate branch to run? have you tested whether starting this action on the main branch will affect the original code of the main branch? I am not sure how this action to submit pr works, will it split into a new branch to submit pr?

2023-02-18 15:58 UTC, yangbobo6 commented
> I have a question, do we need a separate branch to run? have you tested whether starting this action on the main branch will affect the original code of the main branch? I am not sure how this action to submit pr works, will it split into a new branch to submit pr?

This automatically submitted pr, as I understand it, will create a new branch. The name of this branch can be specified with a key in the yaml file, and then compare whether all the codes of the newly created branch are the same as the original branch. If they are the same, delete them. If the newly created branch is different, submit pr.

2023-02-20 03:17 UTC, closed without merging